[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]
nixpkgsArchive = "e05605ec414618eab4a7a6aea8b38f6fde053842"

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn server2:app --host 0.0.0.0 --port ${PORT:-8000}"
